version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  api:
    type: boolean
    default: false
  app:
    type: boolean
    default: false
  auth:
    type: boolean
    default: false
  gateway:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

  build:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>

    steps:
      - checkout:
          path: ~/project
      # This step is added only to show that we are in the package directory
      - run:
          name: Content 
          command: |
            cat README.md 
            echo "<< parameters.package_name >> built." > build.txt
      - run:
          name: Build
          command: echo "Build << parameters.package_name >> ..."
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/<< parameters.package_name >>

  deploy:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>

    steps:
      - attach_workspace:
          at: ~/project
      # This step is added to show that files are available from the build job. 
      - run:
          name: Content to deploy
          command: ls && cat build.txt
      - deploy:
          name: Deploy
          command: echo "Deploying << parameters.package_name >> ..."

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows


  # Workflows defined for each package.

  api:
    when: << pipeline.parameters.api >>
    jobs:
      - build:
          name: api-build
          package_name: api
      - deploy:
          name: api-deploy
          package_name: api
          requires:
            - api-build

  app:
    when: << pipeline.parameters.app >>
    jobs:
      - build:
          name: app-build
          package_name: app
      - deploy:
          name: app-deploy
          package_name: app
          requires:
            - app-build

  auth:
    when: << pipeline.parameters.auth >>
    jobs:
      - build:
          name: auth-build
          package_name: auth
      - deploy:
          name: auth-deploy
          package_name: auth
          requires:
            - auth-build

  gateway:
    when: << pipeline.parameters.gateway >>
    jobs:
      - build:
          name: gateway-build
          package_name: gateway
      - deploy:
          name: gateway-deploy
          package_name: gateway
          requires:
            - gateway-build